name: GitHub Actions Demo
on: [push]
jobs:
  Build_POI_API:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '2.1.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: apis/poi
      - name: Build
        run: dotnet build --no-restore
        working-directory: apis/poi
      - name: Test with the dotnet CLI
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov
        working-directory: apis/poi
      - name: code coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: apis/poi/tests/UnitTests/lcov/coverage.info

