name: UserProfile API
on:
  push:
    branches:
      - feature*
    paths:
      - apis/userprofile/**
      - .github/workflows/userprofile.yaml
  pull_request:
    branches:
      - develop
    paths:
      - apis/userprofile/**
jobs:
  Build_USERPROFILE_API:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup JS
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Test with the JS
        run: npm ci
        working-directory: apis/userprofile
      - if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Error in build',
              body: body
            })
      - name: Push to Azure
        uses: azure/docker-login@v1
        with:
          login-server: 'openhackfho408g7acr.azurecr.io'
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t openhackfho408g7acr.azurecr.io/devopsoh/api-userprofile:${{github.run_number}} --file Dockerfile
          docker push openhackfho408g7acr.azurecr.io/devopsoh/api-userprofile:${{github.run_number}}
        working-directory: apis/userprofile
